using PeWorkshop.Core;

namespace PeWorkshop.App;

public sealed record HelpTopic(string Title, string Meaning, string Usage, string Editing);

/// <summary>Offline explanations for the controls and PE structures displayed by the workshop.</summary>
public static class PeHelpCatalog
{
    private static readonly Dictionary<string, HelpTopic> Topics = CreateTopics();

    public static HelpTopic Get(string key) => Topics.TryGetValue(key, out var topic)
        ? topic : throw new KeyNotFoundException($"No PE help topic exists for '{key}'.");
    public static bool Contains(string key) => Topics.ContainsKey(key);

    public static HelpTopic ForField(PeField field)
    {
        ArgumentNullException.ThrowIfNull(field);
        if (field.Group.StartsWith("Section: ", StringComparison.Ordinal))
            return Get("SectionField." + field.Name);
        if (field.Group.StartsWith("Directory: ", StringComparison.Ordinal))
            return Get(field.Name == "VirtualAddress"
                ? field.Group == "Directory: Certificate" ? "CertificateAddress" : "DirectoryAddress"
                : field.Name == "Size" ? "DirectorySize" : throw new KeyNotFoundException(field.Name));
        return Get("Field." + field.Name);
    }

    public static HelpTopic ForDirectory(int index) => index is >= 0 and < 16
        ? Get("Directory." + index) : throw new ArgumentOutOfRangeException(nameof(index));

    public static HelpTopic ForSection(string name)
    {
        ArgumentNullException.ThrowIfNull(name);
        return Topics.TryGetValue("Section." + name, out var topic) ? topic
            : new("Section " + name,
                "A section groups bytes that the loader maps together, such as code or data. Section names are conventions chosen by the producer; an unfamiliar name does not establish what its contents do.",
                "Compare its permissions, file range and memory range to understand where those bytes live. Reveal opens its file-backed bytes for inspection.",
                "Renaming changes only its eight-byte label. It does not transform the contents or change the section's permissions.");
    }

    private static Dictionary<string, HelpTopic> CreateTopics()
    {
        var result = new Dictionary<string, HelpTopic>(StringComparer.Ordinal);
        void Add(string key, string title, string meaning, string usage, string editing) =>
            result.Add(key, new(title, meaning, usage, editing));
        // Pipe-delimited, authored content: key | title | meaning | practical use | editing/limitations.
        foreach (var line in General.Trim().Split('\n'))
        {
            var parts = line.Trim().Split('|');
            Add(parts[0], parts[1], parts[2], parts[3], parts[4]);
        }
        foreach (var line in Fields.Trim().Split('\n'))
        {
            var parts = line.Trim().Split('|');
            Add(parts[0], parts[1], parts[2], parts[3], parts[4]);
        }
        string[] directoryNames = ["Export", "Import", "Resource", "Exception", "Certificate", "Base relocation", "Debug", "Architecture", "Global pointer", "TLS", "Load configuration", "Bound import", "Import address table", "Delay import", "CLR runtime", "Reserved"];
        string[] directoryMeanings = [
            "Lists symbols this image offers to other modules, by name or ordinal, including symbols forwarded elsewhere.",
            "Describes the modules and symbols requested through the ordinary import table when the image is loaded.",
            "Points to a tree of packaged resources, which can include icons, dialogs, version information and localized text.",
            "Points to architecture-specific exception and unwind information used to walk stacks and handle exceptions.",
            "Locates embedded attribute certificate data used by signing systems such as Authenticode. Its address is a file offset, unlike other directories.",
            "Lists locations that need address adjustments when the loader places an image away from its preferred base.",
            "Locates debug records, which may reference a PDB, describe build information or mark a reproducible build.",
            "This directory is reserved by the PE specification and normally has a zero address and size.",
            "Historically identifies a relative address for a global pointer on architectures that use one; it is usually absent in modern desktop images.",
            "Describes thread-local storage: data and optional callbacks associated with individual threads in a process.",
            "Describes loader configuration, potentially including security-related tables and settings whose layout depends on the structure version.",
            "Contains information recorded when imports were bound to particular dependency versions, as a loader optimization.",
            "Locates slots into which the loader writes the resolved addresses of imported functions or data.",
            "Describes dependencies arranged to be resolved when first needed rather than through ordinary load-time imports.",
            "Locates the managed runtime header used by .NET images, including links to metadata and managed execution information.",
            "This last directory slot is reserved and should have a zero address and size. It is not space for a custom feature."];
        string[] directoryUses = [
            "Use Exports to inspect available names, ordinals, RVAs and forwarders; this helps compare a DLL's public binary interface.",
            "Use Imports to inspect declared dependencies and IAT slots. A listed function is not proof that execution calls it, and dynamic loading may add dependencies not listed here.",
            "Reveal can show the corresponding raw bytes. This app does not decode the resource tree or provide an icon, dialog or version-resource editor.",
            "Reveal locates its raw bytes for structural investigation. The app does not decode unwind records or perform stack walking or disassembly.",
            "Use the overview notice and range to identify declared embedded data. The app does not verify trust, signature validity or catalog signatures; absence here does not imply an unsafe file.",
            "Compare this directory with Image base to learn why rebasing involves more than one header value. The app does not apply relocation records.",
            "Reveal locates raw records. The app does not load a PDB, recover source code or decode all debug types; a timestamp alone is not creation-time proof.",
            "A nonzero entry warrants structural investigation, not a conclusion about CPU type. Use Machine in the COFF header for the declared architecture.",
            "Inspect the address in context with the target Machine field. The app shows this descriptor and raw location but does not emulate global-pointer setup.",
            "Reveal can locate the descriptor. The app does not decode TLS templates or callback arrays, and does not execute callbacks while opening a file.",
            "Use the range to locate configuration bytes. The app does not decode individual mitigation settings or establish that a mitigation operates correctly at runtime.",
            "Reveal shows its bytes for comparison. The app does not decode bound descriptors or locate dependency DLLs to validate their recorded identities.",
            "Compare this range with the per-symbol IAT RVA in Imports. The app reads the file's declarations; it does not show addresses resolved in a running process.",
            "Reveal locates raw descriptors. The Imports view currently decodes ordinary imports only, so this directory can explain dependencies absent from that view.",
            "Its presence is a useful clue that managed metadata exists. The app does not decode .NET types, methods, IL or source code.",
            "Check unexpected values against the producing tool's documentation. The app displays the descriptor but does not assign a custom interpretation to it."];
        for (int i = 0; i < directoryNames.Length; i++)
            Add("Directory." + i, directoryNames[i] + " directory", directoryMeanings[i], directoryUses[i],
                i is 7 or 15 ? "Keep reserved values zero. Editing the descriptor does not create a supported structure."
                : i == 4 ? "Changing this range does not sign the image. Editing signed content can invalidate the signature while leaving certificate bytes present."
                : "The address and size describe existing bytes. Changing them does not rebuild the underlying tables; an inconsistent range can prevent loading or make inspection incomplete.");

        string[] names = [".text", ".rdata", ".data", ".bss", ".rsrc", ".reloc", ".pdata", ".idata", ".edata", ".tls"];
        string[] meanings = [
            "Conventionally holds executable machine instructions produced by a compiler and linker.",
            "Conventionally holds read-only data, such as constant strings, tables and sometimes import-related structures.",
            "Conventionally holds initialized writable data, such as global variables with initial values.",
            "Conventionally represents uninitialized data that needs memory but may require few or no stored file bytes.",
            "Conventionally holds the resource tree containing packaged items such as icons, dialogs or version information.",
            "Conventionally holds base relocation records used when the loader changes the image's placement in memory.",
            "Conventionally holds runtime function records used for exception handling and stack unwinding on some architectures.",
            "Conventionally holds import-related tables, although linkers can place imports in sections with other names.",
            "Conventionally holds export tables describing names, ordinals and addresses made available to other modules.",
            "Conventionally holds thread-local data associated with individual threads rather than shared global storage."];
        for (int i = 0; i < names.Length; i++)
            Add("Section." + names[i], names[i] + " section", meanings[i] + " Names are conventions, not proof of content.",
                "Compare its R/W/X permissions and its raw and virtual ranges. Reveal inspects stored bytes; the app does not execute or disassemble them.",
                "Renaming changes only the label. Moving ranges or changing flags requires matching the real contents and all references to them.");
        return result;
    }

    private const string General = """
CompareHash|Comparison summary and SHA-256|SHA-256 is a cryptographic fingerprint calculated from all file bytes. Different fingerprints establish different bytes, while the differing-position count describes how much this positional comparison changed.|Use the full hashes to identify the snapshots you compared. Read the summary's limitations and parser warnings by scrolling; large finding lists can be capped even though byte counts and hashes cover the full files.|A fingerprint does not establish a publisher, authenticity, intent or safety. Rebuilding or changing a timestamp can change it. A small inserted block may make many subsequent positions differ.
Compare|Compare executables|Compare two PE file snapshots to see changes in headers, sections, directories, declared symbols and actual bytes. Baseline A is the reference; candidate B is examined relative to it.|Choose two files or a supplied sample pair, then select a finding to read its evidence and possible causes. Pink highlights identify unequal bytes or selected evidence.|A static comparison cannot establish an author's intent, prove malicious behavior or recover source code. Different compilers and legitimate feature changes can produce large differences.
CompareBaseline|Baseline A|The reference snapshot used to describe additions, removals and changes in the candidate. A baseline is not automatically trusted or safe.|Choose the earlier or known reference build here. When comparison opens from a loaded editor document, A includes that document's current in-memory bytes, including unsaved edits.|Comparison does not overwrite the baseline. Choosing a different reference reverses the meaning of added and removed; use a trustworthy source when investigating an unexpected change.
CompareCandidate|Candidate B|The second file, whose structure and bytes are compared against baseline A. Candidate means the file being examined, not a verdict about its safety.|Choose the later build or altered copy. Read the path labels before comparing, then inspect differences and their reasons in the findings table.|The file is read as data and never executed by comparison. A different file hash proves different bytes, but does not identify why they differ or whether the change is harmful.
CompareSeverity|Investigation priority|Information explains ordinary differences. Review marks changes that need context. Suspicious highlights patterns such as reduced security declarations or writable executable sections.|Filter to suspicious indicators first when examining the modified training sample, then review other findings for context. Priority is printed as text as well as shown with color.|These are explainable heuristics, not antivirus detections. Legitimate software can trigger them, and their absence does not prove a file safe. Static imports do not prove calls execute.
CompareBytes|Paired evidence bytes|A read-only preview of stored bytes for the selected finding. Each side begins at its own displayed file offset; missing evidence is shown explicitly.|Pink means unequal preview bytes. Amber marks the selected evidence range when the displayed bytes match. Use arrows for further pages, or A/B in editor to inspect a side in the main hex view.|Raw findings compare the same file positions. They do not align inserted blocks, so a small insertion may cause many downstream differences. Neither preview permits editing.
CompareInspect|Inspect comparison evidence|Opens the selected snapshot in the normal hex editor and outlines the evidence range in pink. Amber text still means unsaved edits in the editor.|Choose A in editor or B in editor to inspect the selected finding's bytes. A side without stored evidence has no inspect action. The status bar names the highlighted finding.|Existing unsaved work uses the usual save/discard prompt before switching. Comparison highlights clear when a new file is loaded or an edit is applied, because the finding refers to the earlier snapshot.
CompareSamples|Comparison samples|Two pairs demonstrate ordinary program differences and deliberately suspicious-looking modifications. ConsoleDemo and GuiDemo illustrate different interfaces; OriginalConsole and ModifiedConsole illustrate controlled binary changes.|Use the pair buttons to load files from the Samples folder beside PE-Editor. Read Samples/README.md for the exact changes and source code. All four samples have harmless, documented behavior.|The modified sample is a teaching artifact, not real malware. The comparer uses the same PE rules for arbitrary files; it does not decide findings from these sample filenames or hashes.
Overview|Overview|A summary of the opened file's declared architecture, format, layout and metadata.|Start here to answer whether a file targets x86 or ARM64, where its entry point lies, and whether structural warnings need attention.|This is static inspection: opening a file does not run it. Summary values reflect headers, not a guarantee that Windows can load it.
Headers|Headers|Headers describe how to interpret and load an image. DOS means legacy Disk Operating System; COFF means Common Object File Format. The historically named optional header is required for PE images.|Inspect named fields with their offsets and widths to connect the specification to actual bytes.|Editing changes declarations, not the code or data they describe. Related fields may need coordinated changes.
Sections|Sections|Sections divide the image into ranges of code or data with file locations, memory locations and permission flags.|Compare .text and .data to see why executable code and writable data have different permissions and sizes.|The editor can rename section labels and edit existing header values. It does not rebuild sections, move their contents or update references automatically.
Directories|Directories|Data directories are address-and-size pairs that locate important structures such as imports, exports and resources.|Use a directory to locate a structure even when its section has an unfamiliar name. Its help explains whether the app decodes that structure.|Most addresses are RVAs; the certificate entry uses a file offset. Changing a descriptor does not create or rebuild its payload.
Imports|Imports|Ordinary imports declare modules and symbols that the loader is asked to resolve for this image.|Use them to identify dependencies or investigate a missing-symbol problem. Names can suggest capabilities, but are not proof that a function is called.|This view is read-only. It does not locate DLLs, simulate DLL search, decode delay imports or list functions obtained dynamically at runtime.
Exports|Exports|Exports are names or ordinals the image publishes for other modules to reference.|Compare DLL interfaces, find a symbol's RVA, or recognize that a forwarder redirects a request to another module.|This view is read-only. Export names are a binary interface, not recovered source declarations, and editing arbitrary table bytes can break callers.
Hex|Hex editor|The hex view displays the file as numbered bytes, with text projections alongside them.|Use it to inspect signatures, follow a revealed field, search for a known byte pattern, or compare a small patch.|Replacement preserves length. Bytes may be code, pointers or structured data; readable text alone does not show that a string is safe to replace.
Changes|Changes|The change history records patches made during the current editing session, including their byte ranges and before/after values.|Review this view before saving so you can account for each modification. Undo and Redo help compare an experiment with its starting state.|It is a session history, not a complete audit trail of previous files or build history. Opening another document starts a different editing context.
Open|Open file|Loads a PE file for static inspection and creates the in-memory editing document.|Choose a known EXE or DLL, then begin with Overview and help beside unfamiliar labels. Merely opening it does not execute the selected program.|Unsupported or out-of-range structures may be rejected or reported as diagnostics. Save a separate copy when experimenting.
SaveCopy|Save copy|Writes the current document bytes to a path you choose, preserving the original when you select a different filename.|Use a name such as sample-learning-copy.exe to keep an experiment separate and make it clear which file contains your edits.|A saved copy may no longer load or retain a valid signature. Saving does not validate runtime behavior or automatically update the checksum.
Undo|Undo|Reverses the most recent applied edit in this session and restores its previous bytes.|Use it immediately after a learning experiment or to step back through recorded changes. Inspect Changes to see what was reversed.|Undo acts on document edits, not external programs or files already saved. Save again if you need the restored state written to disk.
Redo|Redo|Reapplies an edit that was reversed with Undo, restoring the same replacement bytes.|Use it to compare the before and after states of a small patch without typing its numeric value again.|Redo availability depends on the session's editing history. It does not prove the reapplied bytes are structurally correct or that the file will run.
UpdateChecksum|Update checksum|Calculates the PE checksum from the current bytes and stores it in the optional header.|Use this after edits when you want the declared checksum to match the copy you are saving, especially when investigating loader checks.|This checksum detects some changes but is not cryptographic signing. Updating it cannot restore an Authenticode signature invalidated by an edit.
Browse|Browse|Opens a file picker so you can select an existing PE image from disk.|Use a program or DLL whose origin you know, or use Explore PE Workshop itself for the guided introduction.|Selection only chooses the file to inspect. Opening parses it statically; the picker does not install or launch the chosen program.
ExploreSelf|Explore PE Workshop itself|Opens the executable associated with this running workshop as a convenient real PE sample.|Use it for the beginner walkthrough: compare its architecture, sections and imports without downloading a sample or running a second program.|Inspection is safe and static. If you experiment with edits, save to a distinct copy; do not replace the running application.
Filter|Filter|Narrows displayed rows by matching text so a large table is easier to inspect.|Try Machine in Headers, .text in Sections, or a DLL name in Imports to find relevant entries quickly.|Filtering changes only the visible selection of rows. It does not remove data from the file or establish that hidden entries are absent.
Reveal|Reveal bytes|Navigates to the file bytes backing the selected item in the hex view.|Use it to connect a field's numeric value or a section's raw range with the actual bytes stored on disk.|Some memory-only RVAs have no file-backed bytes to reveal. Navigation does not edit data; a certificate range is mapped as a file offset.
Edit|Edit numeric field|Opens a focused editor for the existing bytes of a named numeric header field.|Use the field's help to understand its units and consequences before entering a value. Decimal and 0x hexadecimal input make small comparisons convenient.|The field retains its original width and uses little-endian storage. Related structures are not automatically rebuilt when a declaration changes.
RenameSection|Rename section|Changes the eight-byte name stored in a selected section header.|Use this to learn where section labels live or to give an experimental copy an identifiable label; inspect Changes afterward.|Use up to eight ASCII bytes. The name is a convention: renaming .data to .text does not make its contents executable code.
Apply|Apply edit|Commits the dialog's proposed replacement to the current in-memory document.|Check the field name, offset and proposed value first, then apply and inspect Changes or the updated view to understand the result.|Apply changes document bytes, not the original disk file. Input and parse checks cannot establish that all runtime assumptions remain valid.
Cancel|Cancel|Closes the current dialog without applying its proposed edit.|Use this when you opened an editor to inspect the field, entered a tentative value, or decided to read more help before proceeding.|Cancel discards only the current dialog proposal. It does not undo changes applied earlier in the session; use Undo for those.
Go|Go to location|Moves the hex cursor to the requested file offset, or maps an RVA when that address mode is selected.|Use an offset from Headers or an entry-point RVA to inspect surrounding bytes. Select the matching coordinate system before entering the number.|Navigation does not edit bytes. Memory-only RVAs may have no file-backed location; the app reports this rather than inventing stored data.
FindNext|Find next|Searches onward for the next occurrence of the entered byte sequence.|Use it to inspect repeated signatures or text encoded as known bytes. Several matches may exist in unrelated structures.|A match establishes only equal bytes, not their meaning or runtime use. Searching does not modify the document; check the location before any replacement.
Replace|Replace bytes|Overwrites a selected file range with a byte sequence of the same length.|Use a tiny, understood change in a separate copy, then inspect its before/after bytes and try Undo.|This is not insertion or deletion. Preserving length avoids shifting the file, but arbitrary replacements can still damage instructions, addresses, tables or signatures.
Previous|Previous page|Moves the hex view and cursor selection to the preceding page of file bytes.|Use page navigation to inspect data around a range without entering another offset. Check the cursor and page indicators after moving.|This changes navigation only, not file contents. Crossing a display-page boundary does not imply a PE section or structure boundary.
Next|Next page|Moves the hex view and cursor selection to the following page of file bytes.|Use it to continue examining a long section or pattern. Follow the offset labels and cursor indicator to understand the selected file position.|This changes navigation only. File pages here are a viewing convenience, not necessarily the operating system's memory pages.
PE|Portable Executable (PE)|PE is the Windows executable image format used by many EXE, DLL and system files. Headers describe how bytes should be mapped into memory.|Use PE Workshop to learn this layout, inspect declared dependencies and metadata, and make controlled patches to a copy.|It is not a source-code editor, malware verdict or general feature editor. The application reads structures without running the image.
Extensions|File extensions|EXE means executable; DLL means dynamic-link library; SYS commonly identifies a system driver; OCX identifies an ActiveX control; EFI identifies an Extensible Firmware Interface image.|These suffixes suggest intended use. Actual bytes determine whether the file contains a supported PE image; check Format and Machine for structural details.|Renaming a suffix does not convert the format, code or behavior. The parser still requires valid PE headers and supported bounds.
FixedSize|Fixed-size editing|Edits replace bytes while retaining the file's length and existing storage layout.|This is useful for learning individual fields and making narrow, deliberate patches whose location you can review in Changes.|The app does not insert new sections, grow tables or rebuild resources. Equal-length edits can still invalidate references, loading behavior or a signature.
Architecture|Architecture|The COFF Machine value declares the target CPU family, such as x86, x64 or ARM64.|Use this to distinguish a CPU mismatch from an ordinary dependency problem. PE32+ identifies a header format, not a particular CPU family by itself.|Changing Machine does not translate instructions or convert an executable to another architecture. Unknown values require checking the producer and specification.
Format|PE32 / PE32+ format|The optional-header Magic selects PE32 or PE32+, which use different layouts and widths for several values.|Use this when interpreting image base, stack and heap fields. PE32+ uses wider address-related fields but still has 32-bit RVAs.|Changing Magic alone does not convert layouts or code. PE32+ is not synonymous with x64; check Machine for the declared CPU.
FileSize|File size|The number of stored disk bytes, including headers and section data. KiB means kibibyte, or 1,024 bytes; MiB means mebibyte, or 1,048,576 bytes.|Compare it with Image size to see why mapped memory size can differ from disk length.|Fixed-size edits keep file length constant. File size is neither a count of useful code nor the total memory a running process uses.
ImageStructure|Image structure|The overview bar compares sections using their declared raw byte sizes, with a legend linking the section names to explanations.|Use it to see which sections account for most stored section data, then inspect exact file and memory ranges in Sections.|The bar is a size comparison, not a to-scale map of all disk offsets or memory addresses. Section names are conventions; diagnostics remain necessary for structural interpretation.
ImageMetadata|Image metadata|Metadata includes producer-supplied labels and values such as timestamps, checksum and subsystem.|Use it for comparisons between builds and to learn what a linker records. Treat each value according to its own format and purpose.|Metadata can be edited or generated deterministically. It is not proof of provenance, creation time, safety or the program's actual operating-system compatibility.
FileDetails|File details|The overview groups header-location and metadata values such as PE offset, header size, checksum and COFF timestamp.|Use their individual help to connect structural locations with bytes and distinguish a checksum from signing or a timestamp from creation-time proof.|These values are declarations and metadata, not a trust verdict. Editing them does not automatically repair other structures or verify that a saved copy will run.
EntryPoint|Entry point|An RVA identifying the image's initial execution location, or zero when no entry point is declared.|In Hex, select RVA and Go to this value to inspect its mapped startup bytes. The target often contains runtime initialization rather than the source function main.|Revealing the header field shows the value's storage, not target code. Changing it can skip required setup; some targets have no stored bytes and the app does not disassemble instructions.
ImageBase|Image base|The preferred virtual address where the loader would place the image in a process.|Compare it with an RVA: a virtual address is the actual load base plus the RVA. Address randomization can choose another actual base.|Editing this value alone is not complete rebasing. Absolute references and relocation records must remain consistent with the placement.
ImageSize|Image size|SizeOfImage declares the memory span of the loaded image, including headers and aligned sections.|Compare it with file size and section virtual ranges to understand stored bytes versus mapped memory.|It must remain consistent with section ranges and SectionAlignment. Enlarging this number does not create new section data or change the process's total memory use.
Subsystem|Subsystem|Declares the environment expected by the image, for example Windows GUI, Windows console or an EFI environment.|Use this to understand why a typical GUI executable and a console executable have different header values.|Changing this declaration does not add a console interface or adapt code to another environment. Existing startup code and platform assumptions still matter.
PeOffset|PE header offset|The DOS header's e_lfanew value gives the file offset of the PE signature and following headers.|Use it to jump from the initial MZ header to the PE structure rather than assuming a fixed location.|It is a disk offset, not an RVA. Changing it makes the parser and loader look elsewhere; it does not move the actual headers.
HeaderSize|Header size|SizeOfHeaders declares the file range occupied by the DOS, PE, optional and section headers, rounded for file alignment.|Compare it with the section table and first raw section offset to see where structured headers end.|It must contain the real header tables and meet alignment requirements. Changing it does not move tables or insert padding bytes.
Checksum|PE checksum|A non-cryptographic check value stored in the optional header and calculated from file bytes.|Compare the stored value after an edit or use Update checksum to recompute it. Certain image types are subject to loader checksum checks.|This is not a signature or safety verdict. Recomputing it does not restore trust or repair an Authenticode signature invalidated by modified content.
Timestamp|COFF timestamp|A 32-bit producer-supplied value commonly interpreted as seconds since 1970, with special cases and reproducible-build uses.|Use it as one comparison clue between images, alongside other metadata. Zero and 0xFFFFFFFF are not meaningful date/time stamps.|It is not proof of the actual creation time. Changing it only changes recorded bytes and may invalidate signing; it does not rebuild the program.
Diagnostics|Diagnostics|Messages identify structural issues or limits encountered while parsing headers and supported tables.|Use them to locate misaligned ranges, invalid mappings or truncated auxiliary information before trusting a displayed table's completeness.|Warnings are not a malware verdict or complete loader validation. An absence of warnings does not prove that the image will run or is safe.
Certificate|Embedded certificate|The certificate directory declares embedded certificate bytes, often used for Authenticode signing.|Use the notice to recognize that signed-content edits may invalidate a signature. The app reports presence, not trust or cryptographic validity.|Missing embedded data does not exclude a catalog signature or imply unsafe software. Preserving certificate bytes alone does not preserve a valid signature after edits.
Unsaved|Unsaved changes|The document contains edits that have not yet been written through Save copy.|Use Changes to review those edits and choose whether to save the experiment or undo it before switching files.|Save copy preserves the original source and writes a separate destination. This label describes editor state, not whether the proposed copy is valid, signed or runnable.
Field|Field|A named numeric member of a PE structure, with a specific byte location and fixed storage width.|Use the field name, group and contextual help together; the same name can mean different things in COFF, section and directory records.|Editing changes exactly those bytes. A field's valid range depends on its width and on the surrounding structure, not only its numeric type.
Value|Value|The numeric interpretation of a field's bytes, displayed in a form suitable for comparison and editing.|Use hexadecimal to compare masks and addresses with specifications, or decimal when working with counts and sizes.|PE numeric fields use little-endian storage, so displayed hex digits need not appear in the same left-to-right order in the file's hex view.
Offset|File offset|A zero-based byte position measured from the beginning of the file on disk.|Use a field's offset to locate its storage in Hex or compare a change with an external format description.|It is not automatically a loaded memory address or RVA. Replacing bytes at an offset affects that disk position without moving the surrounding contents.
ByteCount|Byte count|The storage width of a field or patch, measured in bytes. One byte holds eight bits.|Use it to distinguish a two-byte flag field from a four-byte address and to select an equal-length replacement.|A field cannot hold values larger than its width permits. Fixed-size replacement cannot grow the field, table or file.
Group|Group|Identifies a field's owning structure. DOS means legacy Disk Operating System; COFF means Common Object File Format. The optional header is historically named and required for PE images.|Use groups to disambiguate names: COFF Characteristics describes the image; section Characteristics describes a section's attributes.|The group is a display label. Editing a value does not rename or move its containing structure.
SectionName|Section name|An eight-byte ASCII label in a section header, often .text or .data.|Use conventional names as clues, then verify with permissions, ranges and directory mappings. A producer can choose different names or combine contents.|Renaming changes only the label. It does not convert data to code, update references or guarantee that all tools treat the renamed section identically.
RVA|Relative virtual address (RVA)|An address relative to the base of the image after it is mapped into memory.|For example, RVA 0x2000 means 0x2000 bytes beyond the actual loaded base. Use section mappings to locate file-backed bytes.|An RVA is usually different from a file offset. Memory-only data can have an RVA without stored bytes; editing a declaration does not move its payload.
VirtualSize|Virtual size|The section's declared size in memory, before section-alignment rounding, measured in bytes.|Compare it with Raw size to see zero-filled memory or file padding. A .bss-like range may need memory without equivalent raw data.|Changing this value does not add stored bytes. Keep it consistent with section mapping, other virtual ranges and SizeOfImage.
RawOffset|Raw file offset|The file position of a section's stored data, represented by PointerToRawData.|Use it to reveal the section's first byte in Hex. This coordinate is measured from the disk file's beginning.|It differs from the section's RVA. Changing the pointer does not move data and can make the loader interpret a different range or an invalid one.
RawSize|Raw size|The number of bytes assigned to a section's stored data, normally rounded to FileAlignment.|Compare it with Virtual size to understand alignment padding and data that will be zero-filled in memory.|Changing this count does not grow or shrink the file. The range must still fit within the file and remain consistent with alignment and other sections.
Permissions|Section permissions|R, W and X summarize whether section flags request readable, writable and executable memory.|Compare .text with .data to understand how code and mutable state are separated. A dash means that permission bit is not set.|These letters show requested section attributes, not proof of runtime access or safety. Changing flags can make existing code fail or expose writable executable memory.
SectionFlags|Section characteristics|A 32-bit mask describing one section's contents and attributes, including read, write and execute requests.|Use the PE section-flags definitions to interpret combined bits; the permissions column shows only the R/W/X subset.|These bits differ from the COFF header's 16-bit Characteristics mask. Editing permissions does not rewrite contents or ensure runtime compatibility.
DirectoryIndex|Directory index|The slot number, from zero to fifteen, which defines a data directory's standardized meaning.|Use index 0 for exports, 1 for imports and 4 for certificates when connecting a specification to displayed rows.|The index is structural, not an editable sort order. Reordering entries would change their interpretation even if their addresses remained unchanged.
DirectoryName|Directory name|A friendly label for a standardized data-directory slot, such as Import or Resource.|Read its help to see what that structure represents and whether the app decodes its contents or only displays its location.|The name comes from the slot's defined meaning, not an embedded string you can rename. A directory can be absent with zero address and size.
DirectoryAddress|Directory address (RVA)|For ordinary directories, this value is the RVA of the structure's beginning in the mapped image.|Use Reveal to follow the declared range when it maps to stored file bytes. The certificate directory is the special file-offset exception.|Changing the address redirects readers to existing bytes. It does not move, create or rebuild the table, and an unmapped address may make it unreadable.
CertificateAddress|Certificate file offset|The certificate directory's address identifies a byte position in the disk file, rather than an RVA in loaded memory.|Use this offset with its size to locate the declared embedded certificate range. Certificates are not loaded like ordinary image sections.|Changing this pointer does not sign the image or verify certificate data. It must identify a valid file range; signing requires a separate signing workflow.
DirectorySize|Directory size|The declared extent, in bytes, of the structure associated with this data-directory entry.|Use it with the address to check the bounds of a table and understand why the app may report an invalid range.|Changing the size does not add, remove or rewrite table records. The descriptor must agree with existing bytes and the format's structure-specific rules.
AddressType|Address type|Identifies the coordinate system of a value: normally RVA for a directory, but file offset for certificates.|In Hex, select File offset or RVA to match the number you are navigating to. Certificate addresses use the File offset mode.|These coordinate systems are not interchangeable. A memory range may have no raw backing, and the app can only reveal addresses that map to stored bytes.
Module|Import module|The dependency module name recorded in an ordinary import descriptor, commonly a DLL name.|Use it to identify declared dependencies or compare imports between builds. The runtime may apply search rules, API-set resolution and other loading behavior.|The app does not locate or load this DLL. The name alone does not prove which physical file will be used or that the dependency is trustworthy.
ImportSymbol|Imported symbol|A function or data name requested from a module; an ordinal-only import is shown with a numeric marker.|Use it to investigate a missing imported symbol or understand a binary's declared interface with its dependencies.|This is a declaration, not evidence that execution calls the function. Dynamic and delay-loaded dependencies may not appear in this ordinary-import table.
ExportSymbol|Exported symbol|A name or ordinal identifying an interface exposed by this image to other modules.|Use it to compare DLL interfaces or locate a specific exported entry. Multiple names can refer to the same address.|An export can be data, code or a forwarder. The app does not recover source types, argument lists or implementation behavior from the name.
Hint|Import hint|A small index hint that can help the loader find an imported name in the target module's export name table.|Use it when comparing raw import records with a specification. It is an optimization hint, not the function's address or public ordinal.|Ordinal-only imports do not use a hint/name record, so the UI shows a dash for their Hint. That dash means not applicable, rather than a missing function address.
IAT|Import address table (IAT) RVA|The relative address of the slot associated with this imported symbol, later used for its resolved address.|Use it to locate the import slot in the file or compare it with the IAT directory's range.|This app inspects file bytes, not a running process. It does not resolve DLLs or show the final function addresses written by the loader.
Ordinal|Ordinal|A numeric identifier used to import or export a symbol without requiring its textual name.|Use it when a library exports entries only by number, or compare an ordinal with a client's declared import.|Ordinals are module-specific identifiers, not file offsets or global function numbers. Changing them can break clients that depend on that particular binary interface.
Forwarder|Export forwarder|An export entry that names another module's symbol rather than pointing directly to this image's implementation.|For example, MODULE.Function or MODULE.#123 redirects symbol resolution elsewhere. Use this to understand an export whose RVA points inside the export directory.|The app displays the string but does not load the destination module or verify resolution. This entry is not ordinary executable code to patch.
Description|Description|A human-readable explanation of a field or edit that supplements its name, location and value.|Use it to understand a change record or relate an abbreviated header name to its structural purpose.|Descriptions are UI text, not evidence about the file's producer or behavior. Detailed field help remains necessary when editing a pointer, size or flag mask.
Before|Before bytes|The original bytes at the recorded patch location before that edit was applied.|Compare them with After to see exactly what changed, including little-endian order for numeric fields.|They describe a particular session edit, not necessarily the original bytes of every file previously opened. Undo uses the recorded prior data for reversible experiments.
After|After bytes|The replacement bytes written at the recorded location by a session edit.|Compare them with Before and inspect the affected field or hex range before saving a copy.|Equal-length patches preserve disk positions but can still change parsing, runtime behavior or signing validity. The history describes the edit, not its correctness.
GoTo|Go to address|The input chooses a location for the hex cursor using the selected File offset or RVA coordinate system.|In File offset mode, enter 0x3C to inspect the DOS e_lfanew storage. In RVA mode, enter the entry-point value to follow its mapped bytes.|An out-of-range offset or memory-only RVA cannot be inspected. Navigation leaves the document unchanged; decimal and 0x-prefixed hexadecimal numbers are accepted.
Search|Search byte pattern or ASCII text|Finds a literal sequence in the file using Hex bytes or ASCII text mode, without interpreting instructions or PE structures.|Search for 4D 5A in Hex bytes mode or a simple DLL name in ASCII text mode. Find next continues onward and wraps to the start.|ASCII search supports characters 0–127. Several matches may have unrelated meanings; equal bytes do not establish runtime use or a safe replacement target.
HexBytes|Hexadecimal bytes|Each pair of hexadecimal digits represents one byte, from 00 through FF. Hex uses digits 0–9 and A–F.|Use this view for exact comparisons with signatures, field storage and patches. For example, 4D 5A is the initial MZ signature.|Numeric PE fields use little-endian byte order. Editing bytes bypasses the meaning of structures, so confirm the range and interpretation first.
ASCII|ASCII text|ASCII means American Standard Code for Information Interchange. It assigns byte values to characters in the range 0–127. The hex view renders printable characters and substitutes placeholders otherwise.|Choose ASCII text search to find a simple name without converting it to byte pairs. Confirm matches using offsets and hex values.|Binary bytes can coincidentally look like text. ASCII search does not decode Unicode strings or determine runtime use.
DecodedText|Decoded text|A text rendering interprets displayed bytes using the view's supported encoding and substitutes or hides unprintable data.|Use it as a reading aid for recognizable strings while keeping byte offsets and hex values as the exact reference.|This is not source recovery, a resource decoder or proof that a program displays the text. Multibyte strings may cross view boundaries.
HexColumns|Hex columns|The column position identifies a byte's displacement within a displayed row; the row address is its starting file offset.|Add the column position to the row offset to locate a byte precisely. This helps compare hex data with an offset listed in Headers.|Rows are a display arrangement, not PE records or instruction boundaries. Selecting a column does not establish the width of a field.
Cursor|Hex cursor|The current selected byte location in the file view, reported as a file offset.|Use it to anchor a replacement or keep track of a revealed field while inspecting neighboring bytes.|A cursor is a viewing selection, not a loaded instruction pointer. Any replacement affects bytes at the chosen disk position, so verify its range.
Page|Hex page|A bounded portion of the file shown at one time to keep inspection responsive and readable.|Use Previous, Next or Go to reach another range while following the page indicator and file offsets.|These are editor display pages, not PE sections or necessarily operating-system memory pages. Changing pages does not modify the file.
ReplacementBytes|Replacement bytes|The exact hexadecimal byte sequence proposed for overwriting an existing range.|Separate byte pairs as the input requires, then compare the proposed count and location before applying. A small patch is easier to review and undo.|The replacement must fit the fixed-size operation. It does not insert text or rebuild structures, and can invalidate a signature even when the file still parses.
NumericInput|Numeric input|A field editor accepts an unsigned numeric value, commonly decimal or hexadecimal prefixed with 0x.|Use decimal for counts and 0x notation for addresses or flag masks. Read the field help to check its units and width.|The value must fit the field's original bytes. Acceptance of a number does not guarantee a valid alignment, mapping, flag combination or runtime behavior.
SectionNames|Section-name input|A section label occupies eight bytes and is interpreted here as ASCII text, with unused bytes padded.|Use a short name such as .learn for a reversible experiment on a copy, then observe the changed section header.|Keep the name within eight ASCII bytes. Renaming a section does not relocate its contents, change permissions, add a feature or rewrite directory references.
""";

    private const string Fields = """
Field.e_lfanew|e_lfanew|This DOS-header field points to the PE signature using a disk file offset.|Reveal shows the four stored bytes; Go to the value to inspect the actual PE header. This connects the initial MZ stub to the Windows image layout.|Changing the pointer does not move headers. An incorrect value can make the entire file fail PE parsing.
Field.Machine|Machine|The COFF target-machine code identifies the CPU family expected by the image.|Compare it with the friendly Architecture label to distinguish x86, x64, ARM64 and hybrid ARM variants. PE32+ alone does not identify the CPU.|Changing this code does not translate machine instructions, calling conventions or runtime dependencies; it cannot convert an architecture.
Field.NumberOfSections|NumberOfSections|The count tells readers how many forty-byte section headers follow the optional header.|Use it to relate the header declaration to the Sections view. PE Workshop supports the Windows limit of up to 96 sections.|Changing the count does not insert or delete section records. A larger count can interpret unrelated bytes as headers or exceed file bounds.
Field.TimeDateStamp|TimeDateStamp|A COFF producer value commonly interpreted as seconds since 1970, with special values and reproducible-build exceptions.|Compare builds using this as one clue rather than proof of creation time. Zero and 0xFFFFFFFF do not represent meaningful timestamps.|A small change is useful for a reversible metadata experiment, but it changes signed content. It does not rebuild code or alter the real creation history.
Field.PointerToSymbolTable|PointerToSymbolTable|A disk offset to a COFF symbol table, or zero when none is declared. This older debugging mechanism is deprecated for executable images.|Use it to distinguish an old COFF symbol reference from modern PDB debug records. The app displays the field but does not decode that symbol table.|Changing it does not generate symbols or recover source names. For images this field should normally be zero.
Field.NumberOfSymbols|NumberOfSymbols|The number of records in the COFF symbol table referenced by PointerToSymbolTable.|Use it with that pointer when investigating legacy structures. It is not a count of imported functions, exports or source-code functions.|This older debugging mechanism is deprecated for images, where the value should normally be zero. Editing the count does not create symbol records.
Field.SizeOfOptionalHeader|SizeOfOptionalHeader|The byte length of the header following COFF, whose name is historical: it is required for these executable images.|Use it to locate the section table and verify that the declared directory records fit within the optional header.|Changing the length shifts where readers expect the section table without moving any bytes. Magic and directory layout must remain consistent with it.
Field.Characteristics|COFF Characteristics|A sixteen-bit mask describing attributes of the overall image, for example executable-image or DLL status.|Use COFF flag definitions to interpret the combined value. These flags are different from a section's thirty-two-bit memory and content attributes.|Setting a DLL flag does not create exports or DLL initialization code. Changing image attributes can conflict with existing startup and loader assumptions.
Field.Magic|Optional-header Magic|The value 0x10B selects PE32; 0x20B selects PE32+. This determines how the optional header is laid out.|Use it to explain why ImageBase and stack/heap sizes have different widths, and why BaseOfData exists only in PE32.|Changing Magic alone does not convert the layout or program. The declared CPU still comes from Machine, not this format marker.
Field.MajorLinkerVersion|MajorLinkerVersion|The major part of the linker version recorded by the image producer.|Compare it with MinorLinkerVersion when investigating build metadata. It may give a toolchain clue, but producers can supply or modify it.|Changing this byte does not rebuild the file with another linker. It is metadata rather than a guarantee about provenance, compatibility or quality.
Field.MinorLinkerVersion|MinorLinkerVersion|The minor part of the producer's recorded linker version, paired with MajorLinkerVersion.|Use the pair as a comparison clue between builds or toolchains, while checking other records for stronger evidence.|Changing it alters recorded metadata only. It does not change machine code or establish which linker actually generated the file.
Field.SizeOfCode|SizeOfCode|The declared total size of code sections, as recorded in the optional header.|Compare it with section raw sizes and code-related flags to understand how the producer summarizes code storage.|It is not a count of instructions or functions. Editing it does not add code, change section contents or disassemble the program.
Field.SizeOfInitializedData|SizeOfInitializedData|The declared aggregate size of initialized data sections, which carry initial bytes in the file.|Compare it with .data and other data-bearing sections to understand the producer's storage summary.|Changing this number does not resize those sections or change their variables. It is not the total memory used by a process while running.
Field.SizeOfUninitializedData|SizeOfUninitializedData|The declared aggregate size of uninitialized data sections, whose memory can be zero-filled rather than fully stored on disk.|Use it with virtual and raw section sizes to see why a memory image can be larger than its file-backed contents.|Changing it does not allocate new variables or rebuild sections. Actual section layout and runtime allocations determine memory use.
Field.AddressOfEntryPoint|AddressOfEntryPoint|The RVA at which initial execution is intended to begin; zero can indicate no entry point.|In Hex, select RVA and Go to this value to inspect mapped startup bytes. Field Reveal shows the value's storage in the header, not target instructions.|Startup is often runtime initialization rather than main. Redirecting it requires valid code and correct setup; changing the value cannot safely select any arbitrary function.
Field.BaseOfCode|BaseOfCode|The RVA marking the beginning of the code area as summarized by the producer.|Compare it with executable sections to connect the optional header to the image layout. It is relative to the image base, not a file pointer.|Editing it does not move code or fix references. The app displays bytes and mappings but does not analyze instructions to validate the declaration.
Field.BaseOfData|BaseOfData|A PE32-only field giving the RVA of the beginning of the data area.|Compare it with writable or initialized-data sections to learn the PE32 layout. PE32+ omits this field rather than giving it a wider version.|Changing it does not move data or update instructions that reference data. It is not interchangeable with PointerToRawData.
Field.ImageBase|ImageBase|The preferred virtual load address, stored in four bytes for PE32 and eight bytes for PE32+.|Use base plus RVA to understand virtual addresses. The actual load address can differ because of relocation or address randomization.|Changing one header field is not complete rebasing: absolute references, relocations and loader requirements must remain consistent.
Field.SectionAlignment|SectionAlignment|The alignment unit, in bytes, used for section placement in the loaded image.|Compare section RVAs and SizeOfImage against it. A typical desktop image aligns mapped sections more broadly than file data.|It must meet PE alignment rules and match the existing layout. Changing it does not repack sections or update their addresses.
Field.FileAlignment|FileAlignment|The alignment unit, in bytes, used for section raw offsets and sizes in the disk file.|Use it to explain padding between stored ranges and why Raw size can exceed useful content.|It must be a valid power of two and consistent with SectionAlignment and the existing ranges. Changing it does not add padding or reposition bytes.
Field.MajorOperatingSystemVersion|MajorOperatingSystemVersion|The major part of the operating-system version recorded in the optional header.|Read it with the minor part when comparing producer metadata. It is not sufficient evidence that the application's APIs work on every version at or above it.|Changing the number does not add support for another OS. Real compatibility depends on code, dependencies and runtime behavior.
Field.MinorOperatingSystemVersion|MinorOperatingSystemVersion|The minor part of the optional header's recorded operating-system version.|Use it alongside the major value to compare declarations between builds. These values do not by themselves prove minimum requirements or tested compatibility.|Editing it changes a header declaration only. It cannot supply missing platform APIs or adapt an application's implementation.
Field.MajorImageVersion|MajorImageVersion|The major part of an image version recorded by the producer in the optional header.|Use it as a build-comparison clue, paired with MinorImageVersion. It is separate from a version-information resource or package version.|Changing it does not edit the resource tree or replace program features. A producer may leave these values at zero or use them differently.
Field.MinorImageVersion|MinorImageVersion|The minor part of the producer-recorded image version, paired with MajorImageVersion.|Compare it between builds while remembering that file version resources may carry different values and are not decoded here.|Editing this field changes only optional-header metadata. It does not update installers, resources or actual program implementation.
Field.MajorSubsystemVersion|MajorSubsystemVersion|The major part of the version recorded for the declared subsystem environment.|Use it with Subsystem and the minor version to interpret loader-related declarations; do not treat it as proof of tested platform support.|Changing a version declaration cannot add missing APIs or make code compatible with a different environment. Loader behavior and application requirements still matter.
Field.MinorSubsystemVersion|MinorSubsystemVersion|The minor part of the version associated with the declared subsystem.|Compare it with the major value when investigating build or loader differences. This field alone does not establish the program's full operating-system requirements.|Editing it may affect how a loader interprets the image but does not adapt program code or verify compatibility.
Field.Win32VersionValue|Win32VersionValue|A reserved optional-header field that should be zero, despite its version-like name.|Use its presence to learn that not every named numeric field is meaningful user metadata. A nonzero value deserves investigation of the producer.|Keep it zero for specification-conforming images. It is not a supported place to write a Windows version or add application behavior.
Field.SizeOfImage|SizeOfImage|The declared total mapped image span, including headers and sections rounded for SectionAlignment.|Compare it with the highest section range and File size to distinguish memory layout from disk storage.|Changing it does not create data or resize sections. An inconsistent or misaligned span can cause structural diagnostics or loader failure.
Field.SizeOfHeaders|SizeOfHeaders|The combined DOS, PE and section-header size, rounded to FileAlignment.|Use it to locate the declared header boundary and compare it with the first raw section range.|It must contain all header records and fit the file. Changing it does not move the section table or repair overlapping ranges.
Field.CheckSum|CheckSum|The stored PE checksum is a non-cryptographic check value calculated over the file.|Use Update checksum after an experiment when you want the saved declaration to match current bytes. Certain image types receive loader checksum checks.|Manually entering a value does not verify it. The checksum is not Authenticode signing and cannot restore a signature invalidated by changed content.
Field.Subsystem|Subsystem|A numeric code identifying the execution environment, such as Windows GUI or Windows console.|Compare GUI and console samples to see how the header expresses their expected environment. It also has values for specialized environments such as EFI.|Changing it does not redesign startup code, add a console workflow or port the program to another platform.
Field.DllCharacteristics|DllCharacteristics|A sixteen-bit optional-header flag mask describing loader and security-related image attributes, including dynamic-base and NX compatibility.|Use the specification to interpret bits and compare builds' declarations. Despite the name, this field also applies to EXE images.|Changing flags does not create the supporting relocation, guard or other tables, nor prove a mitigation works. It is distinct from the COFF DLL flag.
Field.SizeOfStackReserve|SizeOfStackReserve|The declared virtual address space to reserve for the initial stack, using the format's four- or eight-byte width.|Compare it with Stack commit to distinguish reserved space from memory initially committed for use.|Increasing a reserve does not rewrite stack-heavy code or guarantee it cannot overflow. Keep reserve, commit, alignment and platform constraints consistent.
Field.SizeOfStackCommit|SizeOfStackCommit|The declared amount of stack memory initially committed, which can grow within the reserved range.|Use it with Stack reserve to understand initial availability versus maximum reserved address space.|Changing it affects a loader declaration rather than the number of local variables or recursive calls. It must remain sensible relative to the reserve and platform rules.
Field.SizeOfHeapReserve|SizeOfHeapReserve|The declared address-space reserve for the initial process heap, distinct from memory immediately committed.|Compare it with Heap commit when learning how header defaults influence initial allocation setup.|It is not a cap on all allocations made by the program or additional heaps. Editing the number does not solve memory leaks or rewrite allocation behavior.
Field.SizeOfHeapCommit|SizeOfHeapCommit|The declared amount of memory initially committed for the process heap.|Use it with Heap reserve to distinguish initial committed storage from reserved address space and later runtime growth.|Changing this metadata does not determine every heap allocation. Keep it consistent with the reserve and platform constraints; it cannot repair incorrect memory management.
Field.LoaderFlags|LoaderFlags|A reserved optional-header field that should be zero for these images.|Use it as a reminder that some legacy structure members have no supported custom interpretation in modern PE images.|Keep it zero. The app can display its storage but assigning arbitrary bits does not enable documented loader features or implement an application option.
Field.NumberOfRvaAndSizes|NumberOfRvaAndSizes|The number of data-directory address/size pairs declared at the end of the optional header.|Compare it with the Directories view and SizeOfOptionalHeader. PE Workshop displays the first sixteen supported standard entries.|Increasing it does not allocate directory storage or create payloads. The declared records must physically fit inside the existing optional header.
SectionField.VirtualSize|Section VirtualSize|The section's declared size in mapped memory, before final SectionAlignment rounding.|Compare it with SizeOfRawData to recognize file padding or a tail that is zero-filled in memory.|Changing the declaration does not add disk bytes or move other sections. Keep its virtual range consistent with neighboring sections and SizeOfImage.
SectionField.VirtualAddress|Section VirtualAddress|The RVA where this section begins after the image is loaded into memory.|Use it with Raw offset to map an address inside the section to file bytes: raw offset plus the displacement from this RVA.|It is not an absolute virtual address or file pointer. Editing it does not update code references, directories or relocation data that depend on the old location.
SectionField.SizeOfRawData|Section SizeOfRawData|The byte count of this section's stored file range, normally rounded to FileAlignment.|Compare it with VirtualSize to distinguish stored padding from useful mapped data. Uninitialized sections may store little or no raw data.|Changing it does not resize the file. The declared range must fit disk bounds, respect alignment and avoid unintended overlap with other sections.
SectionField.PointerToRawData|Section PointerToRawData|The disk file offset where this section's raw bytes begin, paired with its memory-relative VirtualAddress.|Revealing this field shows the pointer's header storage. Reveal the section row, or use Hex in File offset mode with this value, to inspect its payload.|Changing it redirects readers to existing bytes without moving content. Zero-sized sections may have no meaningful raw range to reveal.
SectionField.PointerToRelocations|Section PointerToRelocations|A file offset to COFF relocation records associated with the section, mainly meaningful in object-file workflows.|Distinguish this legacy section member from the image's Base relocation directory used when loading at another base.|For executable images it should be zero. Editing this pointer does not create base relocations or rebase the image; the app does not decode COFF relocation tables.
SectionField.PointerToLinenumbers|Section PointerToLinenumbers|A file offset to old COFF line-number records, a deprecated debugging mechanism for executable images.|Use it to distinguish historical line records from modern PDB debug information and from source text.|For these images it should be zero. Changing it cannot recover source lines or generate valid debug records, and the app does not decode this table.
SectionField.NumberOfRelocations|Section NumberOfRelocations|The count of the section's COFF relocation records, mainly used for object files before linking.|Use it with PointerToRelocations to interpret the old section-header layout, rather than confusing it with the base relocation directory.|For executable images it should be zero. Changing the count does not create records or adjust absolute references when changing ImageBase.
SectionField.NumberOfLinenumbers|Section NumberOfLinenumbers|The count of legacy COFF line-number entries referenced by this section header.|Use it when comparing historical structure definitions; it is not the count of source-code lines or modern debugging symbols.|This debugging mechanism is deprecated and the value should be zero for executable images. Editing it cannot recover source or build line records.
SectionField.Characteristics|Section Characteristics|A thirty-two-bit mask describing this section's code/data attributes and requested memory permissions.|Use its read, write and execute bits to explain the R/W/X summary, and the PE section-flags definitions for remaining bits.|This mask differs from COFF Characteristics. Changing permissions does not rewrite contents or guarantee the section still meets code and loader assumptions.
""";
}
